common/models/Materials.php
<?php

namespace common\models;

use Yii;

 use yii\helpers\Url; 
class Materials extends \yii\db\ActiveRecord
{
    const UPLOAD_FOLDER='material';
    public static function tableName()
    {
        return 'materials';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['ma_name', 'ma_description', 'ma_price', 'ref'], 'required'],
            [['ma_description'], 'string'],
            [['ma_name', 'ma_price', 'ref'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'ma_name' => 'ชื่อสถานที่',
            'ma_description' => 'รายละเอียด',
            'ma_price' => 'ราคา',
            'ref' => 'Ref',
        ];
    }
    
    
    public static function getUploadPath(){
        //return Yii::$app->basePath . '/../storage/web/'.self::UPLOAD_FOLDER.'/';
        return Yii::getAlias('@webroot').'/'.self::UPLOAD_FOLDER.'/';
       // return Yii::getAlias('@webroot').'/'.self::UPLOAD_FOLDER.'/';
        // $uploadPath = Yii::$app->basePath . '/../storage/web/';  webroot
    }

    public static function getUploadUrl(){
        return Url::base(true).'/'.self::UPLOAD_FOLDER.'/';
    }

    public function getThumbnails($ref,$event_name){
         $uploadFiles   = Uploads::find()->where(['ref'=>$ref])->all();
         $preview = [];
        foreach ($uploadFiles as $file) {
            $preview[] = [
                'url'=>self::getUploadUrl(true).$ref.'/'.$file->real_filename,
                'src'=>self::getUploadUrl(true).$ref.'/thumbnail/'.$file->real_filename,
                'options' => ['title' => $event_name],
                
            ];
        }
        return $preview;
    }
}

backend/controllers/MaterialsController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\Materials;
use backend\models\MaterialsSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

use yii\helpers\Url;
use yii\helpers\html; 
use yii\web\UploadedFile;
use yii\helpers\BaseFileHelper;
use yii\helpers\Json;
use yii\helpers\ArrayHelper;
use yii\db\Query;
use yii\base\ErrorException;
use common\models\Uploads;

class MaterialsController extends Controller
{
     
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    
    public function actionIndex()
    {
        $searchModel = new MaterialsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }
 
    public function actionCreate()
    {
        $model = new Materials();

        if ($model->load(Yii::$app->request->post()) ) {
           
            $this->Uploads(false);

            if($model->save()){
                 return $this->redirect(['index']);
            }
        } else {
             $model->ref = substr(Yii::$app->getSecurity()->generateRandomString(),10);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

     
    public function actionUpdate($id)
    {
       

        $model = $this->findModel($id);

        list($initialPreview,$initialPreviewConfig) = $this->getInitialPreview($model->ref);

        if ($model->load(Yii::$app->request->post())) {
            $this->Uploads(false);

            if($model->save()){
                 return $this->redirect(['index']);
            }
        } 
        
        return $this->render('update', [
            'model' => $model,
             'initialPreview'=>$initialPreview,
             'initialPreviewConfig'=>$initialPreviewConfig
        ]);
    }

    
   public function actionDelete($id)
    {
        
        $model = $this->findModel($id);
        //remove upload file & data
        $this->removeUploadDir($model->ref);
        Uploads::deleteAll(['ref'=>$model->ref]);

        $model->delete();

        return $this->redirect(['index']);
    }

     
    protected function findModel($id)
    {
        if (($model = Materials::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
    
    
     /*|*********************************************************************************|
  |================================ Upload Ajax ====================================|
  |*********************************************************************************|*/

    public function actionUploadajax(){
       // echo 'hello';
        $this->Uploads(true);
     }

    private function CreateDir($folderName){
        if($folderName != NULL){
            $basePath = Materials::getUploadPath();
            if(BaseFileHelper::createDirectory($basePath.$folderName,0777)){
                BaseFileHelper::createDirectory($basePath.$folderName.'/thumbnail',0777);
            }
        }
        return;
    }

    private function removeUploadDir($dir){
        BaseFileHelper::removeDirectory(Materials::getUploadPath().$dir);
    }

    private function Uploads($isAjax=false) {


             if (Yii::$app->request->isPost) {
                $images = \yii\web\UploadedFile::getInstancesByName('upload_ajax');

                

                if ($images) {

                    if($isAjax===true){
                        $ref =Yii::$app->request->post('ref');

                    }else{
                        $Materials = Yii::$app->request->post('Materials');
                        $ref = $Materials['ref'];
                    }
                    
                    $this->CreateDir($ref);
                 
                    //echo json_encode(['success'=>'true']);
                    foreach ($images as $file){
                        $fileName       = $file->baseName . '.' . $file->extension;
                        $realFileName   = md5($file->baseName.time()) . '.' . $file->extension;
                        $savePath       = Materials::UPLOAD_FOLDER.'/'.$ref.'/'. $realFileName;
                        if($file->saveAs($savePath)){

                            if($this->isImage(Url::base(true).'/'.$savePath)){
                                 $this->createThumbnail($ref,$realFileName);
                            }
                          
                            $model                  = new Uploads();
                            $model->ref             = $ref;
                            $model->file_name       = $fileName;
                            $model->real_filename   = $realFileName;
                            $model->save();

                            if($isAjax===true){
                                echo json_encode(['success' => 'true']);
                            }
                            
                        }else{
                            if($isAjax===true){
                                echo json_encode(['success'=>'false','eror'=>$file->error]);
                            }
                        }
                        
                    }

                }


            }
    }

    private function getInitialPreview($ref) {
            $datas = Uploads::find()->where(['ref'=>$ref])->all();
            $initialPreview = [];
            $initialPreviewConfig = [];
            foreach ($datas as $key => $value) {
                array_push($initialPreview, $this->getTemplatePreview($value));
                array_push($initialPreviewConfig, [
                    'caption'=> $value->file_name,
                    'width'  => '120px',
                    'height' => '120px',
                    'url'    => Url::to(['/materials/deletefileajax']),
                    'key'    => $value->upload_id
                ]);
            }
            return  [$initialPreview,$initialPreviewConfig];
    }

    public function isImage($filePath){
            return @is_array(getimagesize($filePath)) ? true : false;
    }

    private function getTemplatePreview(Uploads $model){     
            $filePath = Materials::getUploadUrl().$model->ref.'/thumbnail/'.$model->real_filename;
            $isImage  = $this->isImage($filePath);
            if($isImage){
                $file = Html::img($filePath,['class'=>'file-preview-image', 'alt'=>$model->file_name, 'title'=>$model->file_name,'style'=>'width:100px;']);
            }else{
                $file =  "<div class='file-preview-other'> " .
                         "<h2><i class='glyphicon glyphicon-file'></i></h2>" .
                         "</div>";
            }
            return $file;
    }

    private function createThumbnail($folderName,$fileName,$width=150,$height=150){
      $uploadPath   = Materials::getUploadPath().'/'.$folderName.'/'; 
      $file         = $uploadPath.$fileName;
      $image        = Yii::$app->image->load($file);
      $image->resize($width,$height);
      $image->save($uploadPath.'thumbnail/'.$fileName);
      return;
    }
    
    public function actionDeletefileajax(){

        $model = Uploads::findOne(Yii::$app->request->post('key'));


        if($model!==NULL){
            $filename  = Materials::getUploadPath().$model->ref.'/'.$model->real_filename;
            $thumbnail = Materials::getUploadPath().$model->ref.'/thumbnail/'.$model->real_filename;
            if($model->delete()){
                @unlink($filename);
                @unlink($thumbnail);
                echo json_encode(['success'=>true]);
            }else{
                echo json_encode(['success'=>false]);
            }
        }else{
          echo json_encode(['success'=>false]);  
        }
    } 
    
    
}

frontend/controllers/MaterialController.php
<?php
 

namespace frontend\controllers;
use Yii;

use common\models\User;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;        // เรียกใช้ คลาส AccessControl
use common\components\AccessRule;
use yii\helpers\Url; 
class MaterialController extends \yii\web\Controller{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'denyCallback' => function ($rule, $action) {
                    throw new \yii\web\ForbiddenHttpException("ไม่ได้รับอนุญาตกรุณา Login ");
                },
                'only' => ['order'], // กำหนด action ทั้งหมดภายใน Controller นี้
                'ruleConfig' => [
                    'class' => AccessRule::className() // เรียกใช้งาน accessRule (component) ที่เราสร้างขึ้นใหม่
                ],
                'rules' => [
                    [
                        'actions' => ['order'],     // กำหนด rules ให้ actionIndex()
                        'allow' => true,
                        'roles' => [
                             User::ROLE_USER,        // อนุญาตให้ "user ที่ login" 
                            User::ROLE_ADMIN        // อนุญาตให้ "ผู้ดูแลระบบ" ใช้งานได้
                        ],
                    ],
                     
                ],
            ],
        
        ];
    }//กำหนดให้ login ก่อนถึงจะเข้า method ได้ 

    
    public function actionIndex(){
        
        $query = \common\models\Materials::find();
        $pagination = new \yii\data\Pagination([
            'defaultPageSize'=>10,
            'totalCount'=>$query->count(),
        ]);
        $material = $query->orderBy(['id'=>SORT_DESC])
                ->offset($pagination->offset)
                ->limit($pagination->limit)
                ->all();
        
        
        return $this->render('index',[
            'material'=>$material,
            'pagination'=>$pagination
            
        ]);
         
    }
    
    public function actionOrder($id){
        $order = new \common\models\Orderpromotion();
        $material = \common\models\Materials::findOne($id);
        $post = \yii::$app->request->post();
        $image = \common\models\Uploads::find()->where(['ref'=>$material->ref])->one();
        if(!empty($post))
        {
            
            $count =$post["Orderpromotion"]["count"];
             
            $price = $material->ma_price*$count;
            $order->count = $count;
            $order->user_id = Yii::$app->user->identity->id;
            $order->pro_id = $id;
            $order->pro_name = $material->ma_name;
            $order->total = $price;//
            $order->save(); 

            $report=new \common\models\Reports();
                $report->getReport($id, $material->ma_name, $price, Yii::$app->user->identity->id, $count, Date('Y-m-d'));


            \common\lib\message\Messagebox::getSuccess("บันทึกรายการแล้ว");
            return $this->redirect(['cart/index']);
            
 
            
        }
        return $this->render('order_form',[
            'order'=>$order,
            'img'=>$image,
            'material'=>$material
        ]);
    }//เพิ่มการเลือกสินค้า โปรโมชั่น
}

backend/views/materials/_form.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use kartik\widgets\FileInput; 
?>

<div class="row">

    <?php $form = ActiveForm::begin(); ?>
    <div class="col-md-4">
        <div class="form-group field-upload_files">
      <label class="control-label" for="upload_files[]"> ภาพถ่าย </label>
      <div>
        <?= FileInput::widget([
                   'name' => 'upload_ajax[]',
                     'options' => ['multiple' => true,'accept' => 'image/*'], //'accept' => 'image/*' หากต้องเฉพาะ image
                     'pluginOptions' => [
                     'overwriteInitial'=>false,
                     'initialPreviewShowDelete'=>true,
                     'initialPreview'=> $initialPreview,
                     'initialPreviewConfig'=> $initialPreviewConfig,
                      'uploadUrl' => Url::to(['/materials/uploadajax']),
                     'uploadExtraData' => [
                     'ref' => $model->ref,
                     ],
                     'maxFileCount' => 100
                     ]
                   ]);
                   ?>
               </div>
           </div>
    </div>

    <div class="col-md-6">
     <?= $form->field($model, 'ma_name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'ma_description')->textarea(['rows' => 6]) ?>

 
         <?= $form->field($model, 'ma_price')->textInput(['maxlength' => true]) ?>

     

    <?= $form->field($model, 'ref')->hiddenInput(['maxlength' => 50])->label(false); ?>
<div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Save' : 'Save', ['class' => $model->isNewRecord ? 'btn btn-primary' : 'btn btn-primary']) ?>
    </div>
    </div>
    

    <?php ActiveForm::end(); ?>

</div>

backend/views/materials/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\MaterialsSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="materials-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'ma_name') ?>

    <?= $form->field($model, 'ma_description') ?>

    <?= $form->field($model, 'ma_price') ?>

    <?= $form->field($model, 'ref') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/materials/create.php
<?php

use yii\helpers\Html;
 
$this->title = 'เพิ่ม สถานที่';
$this->params['breadcrumbs'][] = ['label' => 'สถานที่', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="nut">

    <h1><?= Html::encode($this->title) ?></h1>

   <?= $this->render('_form', [
        'model' => $model,
        'initialPreview'=>[],
        'initialPreviewConfig'=>[]
    ]) ?>

</div>

backend/views/materials/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel backend\models\MaterialsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'โปรโมชั่นตกแต่งสถานที่ / รูปแบบงาน';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="nut">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

   <p class="pull-right">
        <?= Html::a('<i class="fa fa-plus"></i> เพิ่มสถานที่', ['create'], ['class' => 'btn btn-primary']) ?>
    </p>
    <div class="clearfix"></div>
<?php Pjax::begin(); ?>    <?=    common\lib\sdii\widgets\SDGridView::widget([
        'dataProvider' => $dataProvider,
        //'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            
            'ma_name',
            'ma_description:ntext',
            'ma_price',
             

            ['class' => 'yii\grid\ActionColumn',
                'header'=>'จัดการ สถานที่',
                'template' => '{view} {update} {delete}',
                'buttons' => [

                    //view button
                    'view' => function ($url, $model) {
			
			    return Html::a('<span class="fa fa-eye"></span> View', $url, [
                                    'title' => Yii::t('app', 'View'),
                                    'class'=>'btn btn-info btn-xs',
			    ]);
			
                    },
                    'update' => function ($url, $model) {
			
			    return Html::a('<span class="glyphicon glyphicon-edit"></span> Edit', $url, [
                                    'title' => Yii::t('app', 'Update'),
                                    'class'=>'btn btn-warning btn-xs',
			    ]);
			
                    },
                    'delete' => function ($url, $model) {
			
			    
			   return Html::a('<span class="fa fa-trash"></span> Delete', $url, [
                                    'title' => Yii::t('app', 'Delete'),
                                    'class'=>'btn btn-danger btn-xs',
                                    'data-confirm' => Yii::t('yii', 'Are you sure you want to delete this item?'),
                                    'data-method' => 'post',                                    
			    ]); 
			    
			 
                    },
                ],
                'contentOptions' => ['style' => 'width:130px;']                
            ],
        ],
    ]); ?>
<?php Pjax::end(); ?></div>

backend/views/materials/update.php
<?php

use yii\helpers\Html;
 
$this->title = 'แก้ไข สถานที่: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'สถานที่', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="nut">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
                'model' => $model,
		         'initialPreview'=>$initialPreview,
		        'initialPreviewConfig'=>$initialPreviewConfig
            ]) ?>

</div>

backend/views/materials/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\Materials */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Materials', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="materials-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'ma_name',
            'ma_description:ntext',
            'ma_price',
            'ref',
        ],
    ]) ?>

</div>