common/models/Weddings.php
<?php

namespace common\models;

use Yii;
use yii\helpers\Url; 
class Weddings extends \yii\db\ActiveRecord
{
    const UPLOAD_FOLDER='weddings';
    public static function tableName()
    {
        return 'weddings';
    }

     
    public function rules()
    {
        return [
            [['we_name', 'we_description', 'we_count', 'we_price', 'ref'], 'required'],
            [['we_description'], 'string'],
            [['we_count'], 'integer'],
            [['we_name', 'we_price', 'ref'], 'string', 'max' => 255],
        ];
    }

     
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'we_name' => 'ชื่อชุดแต่งงาน',
            'we_description' => 'รายละเอียด',
            'we_count' => 'จำนวน',
            'we_price' => 'ราคา',
            'ref' => 'Ref',
        ];
    }
    
    public static function getUploadPath(){
        //return Yii::$app->basePath . '/../storage/web/'.self::UPLOAD_FOLDER.'/';
        return Yii::getAlias('@webroot').'/'.self::UPLOAD_FOLDER.'/';
       // return Yii::getAlias('@webroot').'/'.self::UPLOAD_FOLDER.'/';
        // $uploadPath = Yii::$app->basePath . '/../storage/web/';  webroot
    }

    public static function getUploadUrl(){
        return Url::base(true).'/'.self::UPLOAD_FOLDER.'/';
    }

    public function getThumbnails($ref,$event_name){
         $uploadFiles   = Uploads::find()->where(['ref'=>$ref])->all();
         $preview = [];
        foreach ($uploadFiles as $file) {
            $preview[] = [
                'url'=>self::getUploadUrl(true).$ref.'/'.$file->real_filename,
                'src'=>self::getUploadUrl(true).$ref.'/thumbnail/'.$file->real_filename,
                'options' => ['title' => $event_name],
                
            ];
        }
        return $preview;
    }
    
    
}

backend/controllers/WeddingController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\Weddings;
use backend\models\WeddingSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

use yii\helpers\Url;
use yii\helpers\html; 
use yii\web\UploadedFile;
use yii\helpers\BaseFileHelper;
use yii\helpers\Json;
use yii\helpers\ArrayHelper;
use yii\db\Query;
use yii\base\ErrorException;
use common\models\Uploads;
class WeddingController extends Controller
{
    
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    
    public function actionIndex()
    {
        $searchModel = new WeddingSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Weddings model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

     
    
    
    
    
   public function actionCreate()
    {
        $model = new Weddings();

        if ($model->load(Yii::$app->request->post()) ) {
           
            $this->Uploads(false);

            if($model->save()){
                 return $this->redirect(['index']);
            }
        } else {
             $model->ref = substr(Yii::$app->getSecurity()->generateRandomString(),10);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

     
    public function actionUpdate($id)
    {
       

        $model = $this->findModel($id);

        list($initialPreview,$initialPreviewConfig) = $this->getInitialPreview($model->ref);

        if ($model->load(Yii::$app->request->post())) {
            $this->Uploads(false);

            if($model->save()){
                 return $this->redirect(['index']);
            }
        } 
        
        return $this->render('update', [
            'model' => $model,
             'initialPreview'=>$initialPreview,
             'initialPreviewConfig'=>$initialPreviewConfig
        ]);
    }

    
   public function actionDelete($id)
    {
        
        $model = $this->findModel($id);
        //remove upload file & data
        $this->removeUploadDir($model->ref);
        Uploads::deleteAll(['ref'=>$model->ref]);

        $model->delete();

        return $this->redirect(['index']);
    }
 
     
   

    protected function findModel($id)
    {
        if (($model = Weddings::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
    
    
    
    
    
    
    
    
    /*|*********************************************************************************|
  |================================ Upload Ajax ====================================|
  |*********************************************************************************|*/

    public function actionUploadajax(){
       // echo 'hello';
        $this->Uploads(true);
     }

    private function CreateDir($folderName){
        if($folderName != NULL){
            $basePath = Weddings::getUploadPath();
            if(BaseFileHelper::createDirectory($basePath.$folderName,0777)){
                BaseFileHelper::createDirectory($basePath.$folderName.'/thumbnail',0777);
            }
        }
        return;
    }

    private function removeUploadDir($dir){
        BaseFileHelper::removeDirectory(Weddings::getUploadPath().$dir);
    }

    private function Uploads($isAjax=false) {


             if (Yii::$app->request->isPost) {
                $images = \yii\web\UploadedFile::getInstancesByName('upload_ajax');

                

                if ($images) {

                    if($isAjax===true){
                        $ref =Yii::$app->request->post('ref');

                    }else{
                        $Wedding = Yii::$app->request->post('Weddings');
                        $ref = $Wedding['ref'];
                    }
                    
                    $this->CreateDir($ref);
                 
                    //echo json_encode(['success'=>'true']);
                    foreach ($images as $file){
                        $fileName       = $file->baseName . '.' . $file->extension;
                        $realFileName   = md5($file->baseName.time()) . '.' . $file->extension;
                        $savePath       = Weddings::UPLOAD_FOLDER.'/'.$ref.'/'. $realFileName;
                        if($file->saveAs($savePath)){

                            if($this->isImage(Url::base(true).'/'.$savePath)){
                                 $this->createThumbnail($ref,$realFileName);
                            }
                          
                            $model                  = new Uploads();
                            $model->ref             = $ref;
                            $model->file_name       = $fileName;
                            $model->real_filename   = $realFileName;
                            $model->save();

                            if($isAjax===true){
                                echo json_encode(['success' => 'true']);
                            }
                            
                        }else{
                            if($isAjax===true){
                                echo json_encode(['success'=>'false','eror'=>$file->error]);
                            }
                        }
                        
                    }

                }


            }
    }

    private function getInitialPreview($ref) {
            $datas = Uploads::find()->where(['ref'=>$ref])->all();
            $initialPreview = [];
            $initialPreviewConfig = [];
            foreach ($datas as $key => $value) {
                array_push($initialPreview, $this->getTemplatePreview($value));
                array_push($initialPreviewConfig, [
                    'caption'=> $value->file_name,
                    'width'  => '120px',
                    'height' => '120px',
                    'url'    => Url::to(['/wedding/deletefileajax']),
                    'key'    => $value->upload_id
                ]);
            }
            return  [$initialPreview,$initialPreviewConfig];
    }

    public function isImage($filePath){
            return @is_array(getimagesize($filePath)) ? true : false;
    }

    private function getTemplatePreview(Uploads $model){     
            $filePath = Weddings::getUploadUrl().$model->ref.'/thumbnail/'.$model->real_filename;
            $isImage  = $this->isImage($filePath);
            if($isImage){
                $file = Html::img($filePath,['class'=>'file-preview-image', 'alt'=>$model->file_name, 'title'=>$model->file_name,'style'=>'width:100px;']);
            }else{
                $file =  "<div class='file-preview-other'> " .
                         "<h2><i class='glyphicon glyphicon-file'></i></h2>" .
                         "</div>";
            }
            return $file;
    }

    private function createThumbnail($folderName,$fileName,$width=150,$height=150){
      $uploadPath   = Weddings::getUploadPath().'/'.$folderName.'/'; 
      $file         = $uploadPath.$fileName;
      $image        = Yii::$app->image->load($file);
      $image->resize($width,$height);
      $image->save($uploadPath.'thumbnail/'.$fileName);
      return;
    }
    
    public function actionDeletefileajax(){

        $model = Uploads::findOne(Yii::$app->request->post('key'));


        if($model!==NULL){
            $filename  = Weddings::getUploadPath().$model->ref.'/'.$model->real_filename;
            $thumbnail = Weddings::getUploadPath().$model->ref.'/thumbnail/'.$model->real_filename;
            if($model->delete()){
                @unlink($filename);
                @unlink($thumbnail);
                echo json_encode(['success'=>true]);
            }else{
                echo json_encode(['success'=>false]);
            }
        }else{
          echo json_encode(['success'=>false]);  
        }
    } 
    
    
    
    
}

frontend/controllers/WeddingController.php
<?php
 
namespace frontend\controllers;
use Yii;

use common\models\User;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;        // เรียกใช้ คลาส AccessControl
use common\components\AccessRule;
use yii\helpers\Url; 
class WeddingController extends \yii\web\Controller{

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'denyCallback' => function ($rule, $action) {
                    throw new \yii\web\ForbiddenHttpException("ไม่ได้รับอนุญาตกรุณา Login ");
                },
                'only' => ['order'], // กำหนด action ทั้งหมดภายใน Controller นี้
                'ruleConfig' => [
                    'class' => AccessRule::className() // เรียกใช้งาน accessRule (component) ที่เราสร้างขึ้นใหม่
                ],
                'rules' => [
                    [
                        'actions' => ['order'],     // กำหนด rules ให้ actionIndex()
                        'allow' => true,
                        'roles' => [
                             User::ROLE_USER,        // อนุญาตให้ "user ที่ login" 
                            User::ROLE_ADMIN        // อนุญาตให้ "ผู้ดูแลระบบ" ใช้งานได้
                        ],
                    ],
                     
                ],
            ],
        
        ];
    }//กำหนดให้ login ก่อนถึงจะเข้า method ได้ 
    public function actionIndex(){
        
        $query = \common\models\Weddings::find();
        $pagination = new \yii\data\Pagination([
            'defaultPageSize'=>10,
            'totalCount'=>$query->count(),
        ]);
        $wedding = $query->orderBy(['id'=>SORT_DESC])
                ->offset($pagination->offset)
                ->limit($pagination->limit)
                ->all();
        
        
        return $this->render('index',[
            'wedding'=>$wedding,
            'pagination'=>$pagination
            
        ]);
         
    }//ชุดแต่งงาน เลือกชุดหน้าแรก
    
    public function actionOrder($id){
        $order = new \common\models\Orderpromotion();
        $wedding = \common\models\Weddings::findOne($id);
        $post = \yii::$app->request->post();
        $image = \common\models\Uploads::find()->where(['ref'=>$wedding->ref])->one();
        if(!empty($post))
        {
            
            $count =$post["Orderpromotion"]["count"];
            if($count >  $wedding->we_count){
                \common\lib\message\Messagebox::getWarning("จำนวนชุดเหลือไม่เพียงพอ");
                return $this->render('order_form',[
                    'order'=>$order,
                    'img'=>$image,
                    'wedding'=>$wedding
                ]);
            }
            $price = $wedding->we_price*$count;
            $order->count = $count;
            $order->user_id = Yii::$app->user->identity->id;
            $order->pro_id = $id;
            $order->pro_name = $wedding->we_name;
            $order->total = $price;//
            if($order->save()){
                $c=$wedding->we_count-$count;
                $sql=Yii::$app->db->createCommand("update weddings set we_count='".$c."' where id='".$id."' ")->execute();

                $report=new \common\models\Reports();
                $report->getReport($id, $wedding->we_name, $price, Yii::$app->user->identity->id, $count, Date('Y-m-d'));
            }
            \common\lib\message\Messagebox::getSuccess("บันทึกรายการแล้ว");
            return $this->redirect(['cart/index']);
            
            
            
            
        }
        return $this->render('order_form',[
            'order'=>$order,
            'img'=>$image,
            'wedding'=>$wedding
        ]);
    }//เพิ่มการเลือกสินค้า โปรโมชั่น
}

backend/views/wedding/_form.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use kartik\widgets\FileInput; 
?>

<div class="row">

    <?php $form = ActiveForm::begin(); ?>
    <div class="col-md-4">
        <div class="form-group field-upload_files">
      <label class="control-label" for="upload_files[]"> ภาพถ่าย </label>
      <div>
        <?= FileInput::widget([
                   'name' => 'upload_ajax[]',
                     'options' => ['multiple' => true,'accept' => 'image/*'], //'accept' => 'image/*' หากต้องเฉพาะ image
                     'pluginOptions' => [
                     'overwriteInitial'=>false,
                     'initialPreviewShowDelete'=>true,
                     'initialPreview'=> $initialPreview,
                     'initialPreviewConfig'=> $initialPreviewConfig,
                      'uploadUrl' => Url::to(['/wedding/uploadajax']),
                     'uploadExtraData' => [
                     'ref' => $model->ref,
                     ],
                     'maxFileCount' => 100
                     ]
                   ]);
                   ?>
               </div>
           </div>
    </div>

    <div class="col-md-6">
     <?= $form->field($model, 'we_name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'we_description')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'we_count')->textInput() ?>
         <?= $form->field($model, 'we_price')->textInput(['maxlength' => true]) ?>

     

    <?= $form->field($model, 'ref')->hiddenInput(['maxlength' => 50])->label(false); ?>
<div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Save' : 'Save', ['class' => $model->isNewRecord ? 'btn btn-primary' : 'btn btn-primary']) ?>
    </div>
    </div>
    

    <?php ActiveForm::end(); ?>

</div>

backend/views/wedding/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\WeddingSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="weddings-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'we_name') ?>

    <?= $form->field($model, 'we_description') ?>

    <?= $form->field($model, 'we_count') ?>

    <?= $form->field($model, 'we_image') ?>

    <?php // echo $form->field($model, 'ref') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/wedding/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\Weddings */

$this->title = 'เพิ่ม ชุดแต่งงาน';
$this->params['breadcrumbs'][] = ['label' => 'ชุดแต่งงาน', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="nut">

    <h1><?= Html::encode($this->title) ?></h1>

   <?= $this->render('_form', [
        'model' => $model,
        'initialPreview'=>[],
        'initialPreviewConfig'=>[]
    ]) ?>

</div>

backend/views/wedding/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel backend\models\WeddingSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'ชุดแต่งงาน';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="nut">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p class="pull-right">
        <?= Html::a('<i class="fa fa-plus"></i> เพิ่มชุดแต่งงาน', ['create'], ['class' => 'btn btn-primary']) ?>
    </p>
    <div class="clearfix"></div>
<?php Pjax::begin(); ?>    <?=    \common\lib\sdii\widgets\SDGridView::widget([
        'dataProvider' => $dataProvider,
        //'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

           
            'we_name',
            'we_description:ntext',
            'we_count',
             
            // 'ref',

            ['class' => 'yii\grid\ActionColumn',
                'header'=>'จัดการ ชุดแต่งงาน',
                'template' => '{view} {update} {delete}',
                'buttons' => [

                    //view button
                    'view' => function ($url, $model) {
			
			    return Html::a('<span class="fa fa-eye"></span> View', $url, [
                                    'title' => Yii::t('app', 'View'),
                                    'class'=>'btn btn-info btn-xs',
			    ]);
			
                    },
                    'update' => function ($url, $model) {
			
			    return Html::a('<span class="glyphicon glyphicon-edit"></span> Edit', $url, [
                                    'title' => Yii::t('app', 'Update'),
                                    'class'=>'btn btn-warning btn-xs',
			    ]);
			
                    },
                    'delete' => function ($url, $model) {
			
			    
			   return Html::a('<span class="fa fa-trash"></span> Delete', $url, [
                                    'title' => Yii::t('app', 'Delete'),
                                    'class'=>'btn btn-danger btn-xs',
                                    'data-confirm' => Yii::t('yii', 'Are you sure you want to delete this item?'),
                                    'data-method' => 'post',                                    
			    ]); 
			    
			 
                    },
                ],
                'contentOptions' => ['style' => 'width:130px;']                
            ],
        ],
    ]); ?>
<?php Pjax::end(); ?></div>

backend/views/wedding/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Weddings */

$this->title = 'แก้ไข ชุดแต่งงาน: ' . $model->we_name;
$this->params['breadcrumbs'][] = ['label' => 'ชุดแต่งงาน', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="nut">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
                'model' => $model,
		         'initialPreview'=>$initialPreview,
		        'initialPreviewConfig'=>$initialPreviewConfig
            ]) ?>

</div>

backend/views/wedding/view.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model frontend\models\Photoaul */

$this->title = $model->we_name;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'ภาพกิจกรรม'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="panel" style="width:98%;margin:0 auto; padding:20px;">
<div class="panel-heading">
<a href="<?= Url::to(['index'])?>" class="btn btn-warning btn-sm"><i class="glyphicon glyphicon-menu-left"></i> ย้อนกลับ</a>
        <?php if(@Yii::$app->session['user']->user_status == 20): ?>
         <h1 class="text-center"><?= Html::encode($this->title) ?></h1>
    <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    <?php endif; ?>
</div>
    <ul class="list-group">
        <li class="list-group-item"><b>ชื่อชุดแต่งงาน</b> <?= $model->we_name?></li>
        <li class="list-group-item"><b>รายละเอียด</b> <?= $model->we_description?></li>
        <li class="list-group-item"><b>จำนวน</b> <?= $model->we_count?></li>
        <li class="list-group-item"><b>ราคา</b> <?= number_format($model->we_price,2)?></li>
    </ul>


    <br>
    <div class="text-center">
         <?= dosamigos\gallery\Gallery::widget(['items' => $model->getThumbnails($model->ref,$model->we_name),
    
     ]);?>
    </div>
</div>

<style>
div#w1 {
    
}
div#w1 a img{
       height: 150px;
    width: 150px;
    /* margin: 5px; */
    /* border: 1px solid #c9c9e0; */
    box-shadow: 0px 0px 1px 0px #212135;
    border-radius: 3px;
}
</style>


<style>
.panel-primary {
    border-color: #f65314;
}
.panel-primary > .panel-heading {
    color: #fff;
    background-color: #F65314;
    border-color: #F65314;
    height: 34px;
    line-height: 10px;
}
</style>